# Generated by Django 5.1.6 on 2025-04-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=10, unique=True)),
                ('nome_produto', models.CharField(max_length=250)),
                ('modelo_produto', models.CharField(blank=True, max_length=250, null=True)),
                ('fabricante_produto', models.CharField(blank=True, max_length=250, null=True)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_produto', models.IntegerField()),
                ('descricao_produto', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
