# Generated by Django 5.1.6 on 2025-05-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=250)),
                ('cpf_funcionario', models.CharField(max_length=14, unique=True)),
                ('rg_funcionario', models.CharField(blank=True, max_length=12, null=True)),
                ('endereco_funcionario', models.CharField(max_length=255)),
                ('bairro_funcionario', models.CharField(max_length=100)),
                ('cidade_funcionario', models.CharField(max_length=100)),
                ('telefone_funcionario', models.CharField(blank=True, max_length=15, null=True)),
                ('salario_funcionario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comissao_funcionario', models.IntegerField(blank=True, null=True)),
                ('cargo_funcionario', models.CharField(choices=[('vendedor', 'Vendedor'), ('administrativo', 'Administrativo')], max_length=100)),
                ('status_funcionario', models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado')], default='ativo', max_length=100)),
            ],
        ),
    ]
