# Generated by Django 5.1.6 on 2025-05-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cep_funcionario',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado_funcionario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
