# Generated by Django 5.1.6 on 2025-06-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_cep_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='status_funcionario',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=100),
        ),
    ]
