# Generated by Django 5.1.6 on 2025-02-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('cpf_cnpj_cliente', models.CharField(max_length=14)),
                ('rg_cliente', models.CharField(max_length=12)),
                ('endereco_cliente', models.CharField(max_length=255)),
                ('cep_cliente', models.CharField(max_length=9)),
                ('numero_cliente', models.CharField(max_length=10)),
                ('complemento_cliente', models.CharField(max_length=255)),
                ('bairro_cliente', models.CharField(max_length=100)),
                ('municipio_cliente', models.CharField(max_length=100)),
                ('cidade_cliente', models.CharField(max_length=100)),
                ('estado_cliente', models.CharField(max_length=30)),
                ('telefone_cliente', models.CharField(max_length=15)),
                ('celular_cliente', models.CharField(max_length=15)),
                ('email_cliente', models.EmailField(max_length=255)),
            ],
        ),
    ]
